spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

  application:
    name: ms-message

server:
  port: 8082

netease:
  key: c6848e4951634c76f9becf691c2eb2ec
  secret: 8ec3cd8c31a1
  nonce: 100000